---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: {{ namespace }}
data:
  prometheus.yaml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    rule_files:
    # - "first.rules"
    # - "second.rules"

    alerting:
      alertmanagers:
      - scheme: http
        timeout: 10s
        api_version: v1
        static_configs:
        - targets: []

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: signer
        static_configs:
          - targets: ['{{ serviceName }}.{{ appNamespace }}.svc.cluster.local:8000']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ namespace }}
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yaml
        ports:
        - containerPort: 9090
      volumes:
        - name: prometheus-config
          configMap:
           name: prometheus
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: comermatic
spec:
  selector:
    app: prometheus
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090

