name: branch-rule-attest
on:
  branch_protection_rule:
    types: [created, deleted, edited]
jobs:
    branch-changed:
        runs-on: ubuntu-latest
        steps:
            - id: attest
              run: |
                echo "Hello"

