name: Test bnd setup

on:
  workflow_dispatch:

jobs:
  setup-bnd:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Setup bnd
        uses: carabiner-dev/bnd-actions/setup@HEAD

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Sign Some Stuff
        run: bnd statement attestations/trivy.json
        id: sign

