name: Test bnd setup

on:
  workflow_dispatch:

jobs:
  setup-bnd:
    runs-on: ubuntu-latest

    steps:
      - name: Setup bnd
        uses: carabiner-dev/bnd-actions/setup@HEAD

      - name: Sign Some Stuff
        run: bnd statement si.json
        id: sign

