---
name: SLSA Source
on:
  push:
    branches: [ "master" ]

jobs:
  # Whenever new source is pushed recompute the slsa source information.
  generate-provenance:
    permissions:
      contents: write # needed for storing the vsa in the repo.
      id-token: write
    uses: slsa-framework/slsa-source-poc/actions/slsa_with_provenance@main
